name: Publish

on:
  push:
    tags:
      - 'v*'

env:
  MIMALLOC_CACHE: |
    medvedi/libmimalloc.so*
    medvedi/mimalloc.h

jobs:
  publish:
    name: "Publish release"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: actions/cache
        uses: actions/cache@v3
        with:
          path: ${{ env.MIMALLOC_CACHE }}
          key: ubuntu-22.04-mimalloc-${{ hashFiles('medvedi/mimalloc.h') }}
          restore-keys: ubuntu-22.04-mimalloc-
      - name: mimalloc
        run: make mimalloc
      - name: "Build package"
        run: |
          set +x
          python3 -m pip install --user build twine auditwheel
          python3 -m build
          auditwheel repair --plat manylinux_2_34_x86_64 dist/*.whl
          find dist -name '*linux_x86_64.whl' -delete
      - name: "Publish to PyPI"
        run: |
          set +x
          twine upload wheelhouse/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
